#!/usr/bin/perl

use warnings;
use strict;

use Data::Dumper;

use lib './';
use MediaInfo;

my $filein = $ARGV[0];
#$MediaInfo::med = '/if/your/mediainfo/bin/is/elsewhere/mediainfo';

my $info = mediainfo $filein;

_llog(Dumper($info));

sub _llog
{
	my $msg = shift;

	print $msg."\n";		
}

1;
